## Task 1: Arrays, Statistics, and Indexing

### Task 1.1: Generate an array of 100 random integers

In [ ]:
import numpy as np

np.random.seed(42)

A = np.random.randint(1, 101, 100)

print(A)

### Task 1.2: Statistical analysis of Array A

In [ ]:
print("Minimum:", np.min(A))

print("Maximum:", np.max(A))

print("Mean:", np.mean(A))

print("Median:", np.median(A))

print("Standard Deviation:", np.std(A))

### Task 1.3: Create Array B using np.arange()

In [ ]:
B = np.arange(100)

print(B)

### Task 1.4: Create arrays of zeros and ones

In [ ]:
zeros_array = np.zeros((3, 3))

ones_array = np.ones((3, 3))

print("Zeros Array:")

print(zeros_array)

print()

print("Ones Array:")

print(ones_array)

### Task 1.5: Determine the shape and data type

In [ ]:
print("Shape:", zeros_array.shape)

print("Data Type:", zeros_array.dtype)

### Task 1.6: Compare np.arange() and np.linspace()

In [ ]:
array_arange = np.arange(0, 100, 10)

array_linspace = np.linspace(0, 100, 10)

print("Using np.arange():")

print(array_arange)

print()

print("Using np.linspace():")

print(array_linspace)

print()

print("Difference:")

print("np.arange() uses a fixed step size.")

print("np.linspace() creates a fixed number of equally spaced values.")

### Task 1.7: Create 2D and 3D arrays

In [ ]:
array_2d = np.arange(12).reshape(3, 4)

array_3d = np.arange(24).reshape(2, 3, 4)

print("2D Array:")

print(array_2d)

print()

print("3D Array:")

print(array_3d)

### Task 1.8: Demonstrate indexing and slicing

In [ ]:
print("First Row:")

print(array_2d[0])

print()

print("Second Column:")

print(array_2d[:, 1])

print()

print("Sliced Array:")

print(array_2d[0:2, 1:3])

### Task 1.9: Reshape a matrix

In [ ]:
matrix = np.arange(16).reshape(4, 4)

print(matrix)

### Task 1.10: Flatten the matrix

In [33]:
flattened = matrix.flatten()

print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Task 2 — Vectorized Arithmetic and Linear Algebra

Part 1 — Create two matrices and perform operations

In [34]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Addition
print("\nAddition:")
print(A + B)

# Element-wise multiplication
print("\nElement-wise multiplication:")
print(A * B)

# Matrix multiplication
print("\nMatrix multiplication:")
print(A @ B)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Part 2 — Transpose and Determinant

In [35]:
C = np.array([
    [1, 2],
    [3, 4]
])

# Transpose
transpose = C.T

print("Matrix C:")
print(C)

print("\nTranspose:")
print(transpose)

# Determinant
determinant = np.linalg.det(C)

print("\nDeterminant:")
print(determinant)

Matrix C:
[[1 2]
 [3 4]]

Transpose:
[[1 3]
 [2 4]]

Determinant:
-2.0000000000000004


Part 3 — Find the inverse if the matrix is invertible

In [36]:
if determinant != 0:
    inverse = np.linalg.inv(C)

    print("Inverse of C:")
    print(inverse)
else:
    print("Matrix is not invertible.")

Inverse of C:
[[-2.   1. ]
 [ 1.5 -0.5]]


Part 4 — Verify A @ A⁻¹ using np.allclose()

In [37]:
result = C @ inverse

print("C @ C^-1:")
print(result)

print("\nIs C @ C^-1 equal to Identity Matrix?")
print(np.allclose(result, np.eye(C.shape[0])))

C @ C^-1:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Is C @ C^-1 equal to Identity Matrix?
True


Task 3 – Normal Distribution and Histogram

Part 1 – Generate at least 1,000 values from a normal distribution

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Generate 1000 random values

mean = 50
std = 10

data = np.random.normal(
    loc=mean,
    scale=std,
    size=1000
)

print("Chosen mean:", mean)
print("Chosen standard deviation:", std)

Part 2 – Find the sample mean and sample standard deviation

In [ ]:
sample_mean = np.mean(data)

sample_std = np.std(data, ddof=1)

print("Sample mean:", sample_mean)

print("Sample standard deviation:", sample_std)

print("\nComparison")

print("Chosen mean:", mean)

print("Sample mean:", sample_mean)

print("Chosen standard deviation:", std)

print("Sample standard deviation:", sample_std)

Part 3 – Plot a histogram

In [ ]:
plt.hist(data, bins=30)

plt.xlabel("Values")

plt.ylabel("Frequency")

plt.title("Histogram of Normal Distribution")

plt.show()